Repository SUIN-BUNDANG-LINE/AI, pull requests merged in 2024-10, with the labels that each got.

#7 [SBL-151] 채팅을 통한 설문 일부 수정
  app/core/config/ai_model.py
  app/core/config/chat_memorization.py
  app/core/config/chroma.py
  app/core/prompt/edit/edit_question_prompt.py
  app/core/prompt/edit/edit_section_prompt.py
  app/core/prompt/edit/edit_survey_prompt.py
  app/core/prompt/generate/survey_creation_guide_prompt.py
  app/core/prompt/generate/survey_creation_prompt.py
  app/core/prompt/generate/survey_parsing_prompt.py
  app/core/prompt/prompt_injection_block_prompt.py
  app/core/prompt/survey_parsing_prompt.py
  app/core/util/ai_manager.py
  app/core/util/document_manager.py
  app/core/util/file_manager.py
  app/core/util/function_execution_time_measurer.py
  app/dto/model/question.py
  app/dto/model/question_type.py
  app/dto/model/section.py
  app/dto/model/survey.py
  app/dto/request/edit_question_with_chat_request.py
  app/dto/request/edit_section_with_chat_request.py
  app/dto/request/edit_survey_with_chat_request.py
  app/dto/request/survey_generate_request.py
  app/dto/request/survey_generate_with_file_url_request.py
  app/dto/request/survey_generate_with_text_document_request.py
  app/dto/response/edit_question_with_chat_response.py
  app/dto/response/edit_section_with_chat_response.py
  app/dto/response/edit_total_survey_with_chat_response.py
  app/dto/response/survey_generate_response.py
  app/error/business_exception.py
  app/error/error_code.py
  app/main.py
  app/router/chat_router.py
  app/router/survey_generate_router.py
  app/service/edit_with_chat_service.py
  app/service/survey_generate_serivce.py
  requirements.txt
Labels: 기능구현, 리팩토링

#8 [SBL-173] 설문 요약과 설문 초안 생성을 비동기로 실행하게 구현
  app/core/config/ai_model.py
  app/core/config/chat_memorization.py
  app/core/config/text_spliiter.py
  app/core/prompt/edit/edit_question_prompt.py
  app/core/prompt/edit/edit_section_prompt.py
  app/core/prompt/edit/edit_survey_prompt.py
  app/core/prompt/generate/survey_creation_guide_prompt.py
  app/core/prompt/generate/survey_creation_prompt.py
  app/core/prompt/generate/survey_parsing_prompt.py
  app/core/prompt/prompt_injection_block_prompt.py
  app/core/prompt/summation/document_summation_prompt.py
  app/core/util/ai_manager.py
  app/core/util/document_manager.py
  app/core/util/file_manager.py
  app/core/util/function_execution_time_measurer.py
  app/dto/model/question.py
  app/dto/model/section.py
  app/dto/model/survey.py
  app/dto/request/survey_generate_with_file_url_request.py
  app/dto/request/survey_generate_with_text_document_request.py
  app/dto/response/edit_section_with_chat_response.py
  app/dto/response/edit_total_survey_with_chat_response.py
  app/error/business_exception.py
  app/error/error_code.py
  app/main.py
  app/router/chat_router.py
  app/router/survey_generate_router.py
  app/service/edit_with_chat_service.py
  app/service/survey_generate_serivce.py
  app/service/survey_generate_service.py
Labels: 기능구현, 리팩토링

#9 [SBL-180] dto refactoring
  app/core/prompt/edit/edit_question_prompt.py
  app/core/prompt/edit/edit_section_prompt.py
  app/core/prompt/edit/edit_survey_prompt.py
  app/core/util/ai_manager.py
  app/dto/model/question.py
  app/dto/model/survey.py
  app/dto/request/edit_question_with_chat_request.py
  app/dto/request/edit_section_with_chat_request.py
  app/dto/request/edit_survey_with_chat_request.py
  app/dto/response/edit_question_with_chat_response.py
  app/dto/response/edit_section_with_chat_response.py
  app/dto/response/edit_total_survey_with_chat_response.py
  app/dto/response/survey_generate_response.py
  app/service/edit_with_chat_service.py
  app/service/survey_generate_service.py
Labels: 리팩토링

#13 [SBL-186] dto구조 변경 등
  app/core/prompt/edit/edit_question_prompt.py
  app/core/prompt/edit/edit_section_prompt.py
  app/core/prompt/edit/edit_survey_prompt.py
  app/dto/model/question.py
  app/dto/model/section.py
  app/dto/model/survey.py
  app/service/edit_with_chat_service.py
Labels: 기능구현, 리팩토링

#15 [SBL-197] chat_session_id는 survey_id를 참조하도록 함
  app/core/prompt/edit/edit_question_prompt.py
  app/core/prompt/edit/edit_section_prompt.py
  app/core/prompt/edit/edit_survey_prompt.py
  app/core/prompt/generate/survey_creation_prompt.py
  app/core/util/ai_manager.py
  app/dto/model/question.py
  app/dto/model/section.py
  app/dto/model/survey.py
  app/dto/request/survey_generate_with_file_url_request.py
  app/dto/request/survey_generate_with_text_document_request.py
  app/dto/response/survey_generate_response.py
  app/service/edit_with_chat_service.py
  app/service/survey_generate_service.py
Labels: 기능구현

#17 [SBL-179] 전체적인 리팩토링
  app/core/config/ai_model.py
  app/core/config/chroma.py
  app/core/config/text_spliiter.py
  app/core/error/business_exception.py
  app/core/error/error_code.py
  app/core/prompt/edit/edit_question_prompt.py
  app/core/prompt/edit/edit_section_prompt.py
  app/core/prompt/edit/edit_survey_prompt.py
  app/core/prompt/generate/survey_creation_guide_prompt.py
  app/core/prompt/generate/survey_creation_prompt.py
  app/core/prompt/generate/survey_parsing_prompt.py
  app/core/prompt/summation/document_summation_prompt.py
  app/core/util/ai_manager.py
  app/core/util/document_manager.py
  app/core/util/function_execution_time_measurer.py
  app/dto/request/survey_generate_with_file_url_request.py
  app/dto/request/survey_generate_with_text_document_request.py
  app/service/edit_with_chat_service.py
  app/service/survey_generate_service.py
Labels: 리팩토링

#18 0.0.8
  app/core/config/ai_model.py
  app/core/config/chroma.py
  app/core/config/text_spliiter.py
  app/core/error/business_exception.py
  app/core/error/error_code.py
  app/core/prompt/edit/edit_question_prompt.py
  app/core/prompt/edit/edit_section_prompt.py
  app/core/prompt/edit/edit_survey_prompt.py
  app/core/prompt/generate/survey_creation_guide_prompt.py
  app/core/prompt/generate/survey_creation_prompt.py
  app/core/prompt/generate/survey_parsing_prompt.py
  app/core/prompt/summation/document_summation_prompt.py
  app/core/util/ai_manager.py
  app/core/util/document_manager.py
  app/core/util/function_execution_time_measurer.py
  app/dto/request/survey_generate_with_file_url_request.py
  app/dto/request/survey_generate_with_text_document_request.py
  app/service/edit_with_chat_service.py
  app/service/survey_generate_service.py
Labels: 배포

#21 [SBL-213] pptx, docx로 설문조사 생성
  app/core/util/document_manager.py
  app/core/util/user_prompt_resolve_chat.py
  app/dto/request/survey_generate_with_file_url_request.py
  requirements.txt
Labels: 기능구현

#29 [SBL-218] file url nullable과 바뀌는 비즈니스 로직 반영
  app/core/error/error_code.py
  app/core/prompt/edit/edit_question_prompt.py
  app/core/prompt/edit/edit_section_prompt.py
  app/core/prompt/edit/edit_survey_prompt.py
  app/core/prompt/survey_creation_prompt.py
  app/core/util/ai_manager.py
  app/dto/model/survey.py
  app/dto/request/survey_generate_request.py
  app/dto/request/survey_generate_with_text_document_request.py
  app/router/survey_generate_router.py
  app/service/edit_with_chat_service.py
  app/service/survey_generate_service.py
Labels: 기능구현, 리팩토링

#30 [SBL-220] edit reason
  app/core/prompt/edit/edit_question_prompt.py
  app/core/prompt/edit/edit_section_prompt.py
  app/core/prompt/edit/edit_survey_prompt.py
  app/core/util/allowed_other_manager.py
  app/dto/response/edit_question_with_chat_response.py
  app/dto/response/edit_section_with_chat_response.py
  app/dto/response/edit_total_survey_with_chat_response.py
  app/service/edit_with_chat_service.py
Labels: 기능구현
